# Generated by Django 2.2.5 on 2020-02-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('pub_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='date of publication')),
                ('votes_total', models.IntegerField(default=0, verbose_name='total votes')),
                ('image', models.ImageField(upload_to='images/')),
                ('icon', models.ImageField(upload_to='images/')),
                ('body', models.TextField()),
            ],
        ),
    ]
