# Generated by Django 2.2.5 on 2020-02-08 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200207_2001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
